export interface IPriprema {
  skolskaGodina: string,
  nastavnik: string,
  razred: string,
  predmet: string,
  datum: string | undefined,
  nastavnaOblast: string,
  nastavnaJedinica: string,
  ciljeviOdgojni: string,
  ciljeviObrazovni: string,
  ciljeviFunkcionalni: string,
  ciljeviDuhovni: string,
  strukturaCasa: string,
  tipCasa: string,
  obliciNastavnogRada: string,
  nastavniObjekti: string,
  nastavniPomagala: string,
  korelacija: string,
  lokacija: string,
  planTable: string,
  literatura: string,
  nastavneMetode: string,
  uvodniTrajanje: string,
  uvodniSadrzaj: string,
  glavniTrajanje: string,
  glavniSadrzaj: string,
  zavrsniTrajanje: string,
  zavrsniSadrzaj: string,
  domaciRad: string,
  korekcija: string,
  _id?: string
}