import { IPriprema } from "types/Priprema";

export let defaultPriprema: IPriprema = {
  skolskaGodina: '',
  nastavnik: '',
  razred: '',
  predmet: '',
  datum: '',
  nastavnaOblast: '',
  nastavnaJedinica: '',
  ciljeviOdgojni: '',
  ciljeviObrazovni: '',
  ciljeviFunkcionalni: '',
  ciljeviDuhovni: '',
  strukturaCasa: '',
  tipCasa: '',
  obliciNastavnogRada: '',
  nastavniObjekti: '',
  nastavniPomagala: '',
  korelacija: '',
  lokacija: '',
  planTable: '',
  literatura: '',
  nastavneMetode: '',
  uvodniTrajanje: '',
  uvodniSadrzaj: '',
  glavniTrajanje: '',
  glavniSadrzaj: '',
  zavrsniTrajanje: '',
  zavrsniSadrzaj: '',
  domaciRad: '',
  korekcija: '',
  _id: ''
}